server {
  listen 80;
  absolute_redirect off;
  include /etc/nginx/mime.types;
  types { application/manifest+json webmanifest; }
  root /usr/share/nginx/html;

  include /etc/nginx/smallhill-servers.conf;

  location ~ (^|/)(index\.html|ngsw\.json|ngsw-worker\.js|manifest\.webmanifest)$ {
    add_header Cache-Control "no-cache";
  }

  location ~ ^/(?<app>[^/]+)/ {
    try_files $uri $uri/ /$app/index.html /index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
