name: Scheduler

on:
  pull_request:
    paths:
      - "apps/scheduler/**"
      - ".github/workflows/app.scheduler.yaml"
  push:
    branches:
      - master
    paths:
      - "apps/scheduler/**"
      - ".github/workflows/app.scheduler.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    uses: ./.github/workflows/_test.yaml
    with:
      app: scheduler
      postgres: true
