name: Portal

on:
  pull_request:
    paths:
      - "apps/portal/**"
      - ".github/workflows/app.portal.yaml"
  push:
    branches:
      - master
    paths:
      - "apps/portal/**"
      - ".github/workflows/app.portal.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    uses: ./.github/workflows/_test.yaml
    with:
      app: portal
      postgres: false
