name: Tuner

on:
  pull_request:
    paths:
      - "apps/tuner/**"
      - ".github/workflows/app.tuner.yaml"
  push:
    branches:
      - master
    paths:
      - "apps/tuner/**"
      - ".github/workflows/app.tuner.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    uses: ./.github/workflows/_test.yaml
    with:
      app: tuner
      postgres: false
