name: Bump version
run-name: Bump version (${{ inputs.app }})

on:
  workflow_dispatch:
    inputs:
      app:
        description: "App to release"
        required: true
        type: choice
        options:
          - portal
          - scheduler
          - tuner
      semver:
        description: "Version bump"
        required: true
        type: choice
        default: none
        options:
          - none
          - patch
          - minor
          - major
      # prerelease:
      #   description: "Prerelease version"
      #   type: boolean
      #   required: false
      #   default: false

concurrency:
  group: ${{ github.workflow }}-${{ inputs.app }}
  cancel-in-progress: true

jobs:
  version:
    name: Resolve version
    uses: ./.github/workflows/_version.yaml
    with:
      app: ${{ inputs.app }}
      semver: ${{ inputs.semver }}
      # prerelease: ${{ github.event.inputs.prerelease }}

  tag:
    name: Tag
    needs: version
    uses: ./.github/workflows/_tag.yaml
    with:
      tag: ${{ inputs.app }}-PRODUCTION
      version: ${{ needs.version.outputs.version }}
