name: Release to DEV
run-name: Release to DEV (${{ inputs.app }})

on:
  workflow_dispatch:
    inputs:
      app:
        description: "App to release"
        required: true
        type: choice
        options:
          - portal
          - scheduler
          - tuner

concurrency:
  group: ${{ github.workflow }}-${{ inputs.app }}
  cancel-in-progress: true

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_short_sha.outputs.short_sha }}
    steps:
      - name: Set short SHA
        id: set_short_sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  build:
    name: Build
    needs:
      - version
    uses: ./.github/workflows/_build.yaml
    with:
      app: ${{ inputs.app }}
      image: ghcr.io/smallhillcz/smallhill-apps-${{ inputs.app }}:dev
      version: DEV-${{ needs.version.outputs.version }}

  cleanup:
    name: Clean up
    needs:
      - build
    uses: ./.github/workflows/_cleanup.yaml
    with:
      package: smallhill-apps-${{ inputs.app }}

  deploy:
    name: Deploy
    needs:
      - build
    uses: ./.github/workflows/_deploy.yml
    with:
      images: ghcr.io/smallhillcz/smallhill-apps-${{ inputs.app }}:dev
    secrets: inherit

  tag:
    name: Tag
    needs:
      - build
    uses: ./.github/workflows/_tag.yaml
    with:
      tag: ${{ inputs.app }}-DEV
