name: Release to PRODUCTION
run-name: Release to PRODUCTION (${{ inputs.app }})

on:
  workflow_dispatch:
    inputs:
      app:
        description: "App to release"
        required: true
        type: choice
        options:
          - portal
          - scheduler
          - tuner
      semver:
        description: "Version bump"
        required: true
        type: choice
        default: none
        options:
          - none
          - patch
          - minor
          - major

concurrency:
  group: ${{ github.workflow }}-${{ inputs.app }}
  cancel-in-progress: true

jobs:
  version:
    name: Resolve version
    uses: ./.github/workflows/_version.yaml
    with:
      app: ${{ inputs.app }}
      semver: ${{ inputs.semver }}

  build:
    name: Build
    needs:
      - version
    uses: ./.github/workflows/_build.yaml
    with:
      app: ${{ inputs.app }}
      image: ghcr.io/smallhillcz/smallhill-apps-${{ inputs.app }}:latest
      version: ${{ needs.version.outputs.version }}

  cleanup:
    name: Clean up
    needs:
      - build
    uses: ./.github/workflows/_cleanup.yaml
    with:
      package: smallhill-apps-${{ inputs.app }}

  deploy:
    name: Deploy
    needs:
      - build
    uses: ./.github/workflows/_deploy.yml
    with:
      images: ghcr.io/smallhillcz/smallhill-apps-${{ inputs.app }}:latest
    secrets: inherit

  tag:
    name: Tag
    needs:
      - build
      - version
    uses: ./.github/workflows/_tag.yaml
    with:
      tag: ${{ inputs.app }}-PRODUCTION
      version: ${{ inputs.semver != 'none' && needs.version.outputs.version || '' }}
