name: Release to PRODUCTION

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "Version bump"
        required: true
        type: choice
        default: none
        options:
          - none
          - patch
          - minor
          - major

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  version:
    name: Resolve version
    uses: ./.github/workflows/_version.yaml
    with:
      semver: ${{ github.event.inputs.semver }}

  build:
    name: Build
    needs:
      - version
    uses: ./.github/workflows/_build.yaml
    with:
      host: ${{ vars.APPS_HOST || 'apps.smallhill.cz' }}
      router: smallhill-apps-prod
      image: ghcr.io/smallhillcz/smallhill-apps:latest
      version: ${{ needs.version.outputs.version }}

  cleanup:
    name: Clean up
    needs:
      - build
    uses: ./.github/workflows/_cleanup.yaml
    with:
      package: smallhill-apps

  deploy:
    name: Deploy
    needs:
      - build
    uses: ./.github/workflows/_deploy.yml
    with:
      images: ghcr.io/smallhillcz/smallhill-apps:latest
    secrets: inherit

  tag:
    name: Tag
    needs:
      - build
      - version
    uses: ./.github/workflows/_tag.yaml
    with:
      tag: PRODUCTION
      version: ${{ github.event.inputs.semver != 'none' && needs.version.outputs.version || '' }}
